# Codecov Configuration
# Story 9.8.10: CI/CD Integration

coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 2%
    patch:
      default:
        target: 60%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/__tests__/**"
  - "**/e2e/**"
  - "**/*.config.ts"
  - "**/*.config.js"
  - "**/vite.config.ts"
  - "**/vitest.config.ts"
  - "**/playwright.config.ts"

flags:
  unit:
    paths:
      - src/
    carryforward: true
  integration:
    paths:
      - src/__tests__/integration/
    carryforward: true
